#!/usr/bin/env bash
alias vim="$VIM"
alias pass="gopass"
alias awrc="cd $AWESOME_DIR && $EDITOR ."
alias vimrc="cd $NVIM_DIR && $EDITOR ."
alias dev="cd $HOME/development"
alias todo="$EDITOR $HOME/vaults/notes/todo.md"
