#!/usr/bin/env bash
alias vim="$VIM"
alias awrc="cd $AWESOME_DIR && $EDITOR ."
alias vimrc="cd $NVIM_DIR && $EDITOR ."
alias dev="cd $HOME/development"
alias todow="cd $HOME/vaults/work && $EDITOR todo.md"
alias todop="cd $HOME/vaults/personal && $EDITOR todo.md"
